### PR TITLE
Support for aws-sdk-dynamodb 1

### PR DESCRIPTION
**Pull request by vmaerten**

### CODE REVIEW

**Comment by dcormier** [comment]
Should this feature perhaps be `"aws-sdk-dynamodb+1"`, with `aws-sdk-dynamodb` crate version `1` being enabled? This should allow the dependant crate to use any minor revision of `aws-sdk-dynamodb` v1.

**Comment by vmaerten** [comment]
Can be good, but i'm not sure they won't change anything in the SDK
What do you thing @bryanburgers ?

**Comment by vmaerten** [comment]
I've updated to match create version 1

They also did like that in Opensearch rs (https://github.com/opensearch-project/opensearch-rs/blob/main/opensearch/Cargo.toml#L43-L46)

**Comment by bryanburgers** [comment]
Yeah. I strongly support doing just `1`, not `1.2`. Then we can get off of this version treadmill!

I’m also strongly considering supporting aws-sdk-DynamoDB 1 _without_ a feature flag.

* aws-sdk-dynamodb is stable
* rusoto is dead
* aws-lambda-events uses serde_dynamo directly

Given those three, it seems like serde_dynamo could just be stable at this point?

**Comment by bryanburgers** [comment]
But I’ll at least make a release with the feature flag first. And then decide what to do.

**Comment by bryanburgers** [comment]
Released in version 4.2.13

**Pull request merged**
