### PR TITLE
Update aws_sdk to 0.6

### PR DESCRIPTION
**Pull request by sciguy16**
Hi! Thanks for the library - just noticed aws_sdk has been version bumped again, so I've made similar changes to #19 to add a feature for 0.5.

cc #9

### CODE REVIEW

**Comment by steveocr** [comment]
Might as well bump it to 0.6 now?

**Comment by sciguy16** [comment]
Good spot, I'll add 0.6

**Comment by sciguy16** [comment]
Hey @bryanburgers, please could you review this if you have some time?

**Comment by bryanburgers** [comment]
Thank you! Merged and published! ✅

**Pull request merged**
